#pragma once
#include <wdm.h>

#define TIME_DEVICE_TYPE 0x8003

#define IOCTL_TIME_PING           CTL_CODE(TIME_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TIME_GET_VERSION    CTL_CODE(TIME_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TIME_GET_SNAPSHOT   CTL_CODE(TIME_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _TIME_VERSION { ULONG Major, Minor, Patch; } TIME_VERSION, *PTIME_VERSION;

typedef struct _TIME_SNAPSHOT
{
    LONGLONG SystemTime100ns;
    ULONGLONG InterruptTime100ns;
    ULONG BuildNumber;
} TIME_SNAPSHOT, *PTIME_SNAPSHOT;
