#pragma once
#include <wdm.h>

#define STATS_DEVICE_TYPE 0x8002

#define IOCTL_STATS_PING            CTL_CODE(STATS_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STATS_GET_VERSION     CTL_CODE(STATS_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STATS_GET_COUNTERS    CTL_CODE(STATS_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STATS_RESET_COUNTERS  CTL_CODE(STATS_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _STATS_VERSION { ULONG Major, Minor, Patch; } STATS_VERSION, *PSTATS_VERSION;

typedef struct _STATS_COUNTERS
{
    ULONGLONG IoctlPing;
    ULONGLONG IoctlGetVersion;
    ULONGLONG IoctlGetCounters;
    ULONGLONG IoctlResetCounters;
    ULONGLONG InvalidIoctl;
} STATS_COUNTERS, *PSTATS_COUNTERS;
