#pragma once
#include <wdm.h>

#define NOTIFY_DEVICE_TYPE 0x8001

#define IOCTL_NOTIFY_PING            CTL_CODE(NOTIFY_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NOTIFY_GET_VERSION     CTL_CODE(NOTIFY_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NOTIFY_SET_EVENT       CTL_CODE(NOTIFY_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NOTIFY_CLEAR_EVENT     CTL_CODE(NOTIFY_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NOTIFY_TRIGGER         CTL_CODE(NOTIFY_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _NOTIFY_VERSION
{
    ULONG Major;
    ULONG Minor;
    ULONG Patch;
} NOTIFY_VERSION, *PNOTIFY_VERSION;

typedef struct _NOTIFY_SET_EVENT_INPUT
{
    HANDLE EventHandle;
} NOTIFY_SET_EVENT_INPUT, *PNOTIFY_SET_EVENT_INPUT;
